name: build-cd-pre-release

on:
  # schedule:
  #   # every week sunday
  #   - cron:  '0 0 * * 0'

  push:
    branches:
    tags-ignore:
      - "*"

  workflow_dispatch:
    inputs:
      name:
        description: "Build alias"
        required: true
        default: "apptool"


jobs:
  build-cd-publish:
    #if: github.ref == 'refs/heads/main'
    #windows-latest
    #if you publish has windows ,you need use Windows image to build, that output file has metedata ,eg fileversion.
    runs-on: ubuntu-latest

    env:
      MINVERBUILDMETADATA: ${{github.run_id}}

    strategy:
      matrix:
        RuntimeIdentifier:
          [win-x64, win-x86]
          #, linux-x64, linux-musl-x64, linux-arm, linux-arm64

    steps:
      - run: echo "GITHUB_REF  $GITHUB_REF GITHUB_EVENT_NAME $GITHUB_EVENT_NAME  GITHUB_EVENT_PATH $GITHUB_EVENT_PATH GITHUB_ACTION $GITHUB_ACTION   GITHUB_RUN_ID $GITHUB_RUN_ID GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER"

      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: cd src &&  dotnet publish -c Release -r $RuntimeIdentifier -p:PublishSingleFile=true --self-contained true  -o ../publish/$RuntimeIdentifier
        env:
          RuntimeIdentifier: ${{ matrix.RuntimeIdentifier }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.RuntimeIdentifier}}
          retention-days: 1
          path: ./publish/${{matrix.RuntimeIdentifier}}/*

  build-cd-upload:
    needs: build-cd-publish
    runs-on: ubuntu-latest

    steps:
      - run: echo "GITHUB_REF  $GITHUB_REF GITHUB_EVENT_NAME $GITHUB_EVENT_NAME  GITHUB_EVENT_PATH $GITHUB_EVENT_PATH GITHUB_ACTION $GITHUB_ACTION   GITHUB_RUN_ID $GITHUB_RUN_ID GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER"

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          path: ./publish/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./publish/

      - name: Package Release
        run: ./scripts/publishpackage.ps1
        shell: pwsh
        env:
          publishdir: ./publish
          prefix:  ${{ github.event.inputs.name }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "preview"
          title: "Auto Build ${{ github.run_id }}-${{ github.run_number }}"
          prerelease: true
          files: ./publish/*.zip
